[global]
type=global
user_agent=QTalk Asterisk

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5070

; =========================
; Абонент 100 — QTalk
; =========================

[100]
type=endpoint
transport=transport-tcp
context=qtalk
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=100-auth
aors=100
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[100-auth]
type=auth
auth_type=userpass
username=100
password=qtalk100

[100]
type=aor
max_contacts=1
remove_existing=yes


; =========================
; Абонент 101 — второй клиент
; =========================

[101]
type=endpoint
transport=transport-tcp
context=qtalk
disallow=all
allow=opus
allow=ulaw
allow=alaw
auth=101-auth
aors=101
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[101-auth]
type=auth
auth_type=userpass
username=101
password=qtalk101

[101]
type=aor
max_contacts=1
remove_existing=yes
